version: "3.9"
services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./apps:/var/www
    depends_on:
      - php-fpm 
  php-fpm:
    container_name: php-fpm
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./apps/site1:/var/www/site1
      - ./apps/site2:/var/www/site2
    ports:
      - "9000:9000"
  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./apps:/app
    command: tail -f /dev/null
    restart: always
  node:
    container_name: node
    image: node:latest
    volumes:
      - ./apps/site1:/app
    working_dir: /app
    command: npm run watch
    restart: always
    ports:
      - 8080:5173
  db:
    image: mysql:latest
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testes
      MYSQL_USER: miguel
      MYSQL_PASSWORD: miguel
    volumes:
      - ./db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
  
  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    container_name: my-phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "9098:80"
    depends_on:
      - db
